import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('vi'),
    Locale('ja'),
    Locale('ko'),
    Locale('zh'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return localizations ?? const AppLocalizations(Locale('en'));
  }

  String _t(String key) {
    final lang = locale.languageCode;
    final table = _localizedValues[lang] ?? _localizedValues['en']!;
    return table[key] ?? _localizedValues['en']![key] ?? key;
  }

  String t(String key) => _t(key);

  String devicesCount(int count) {
    switch (locale.languageCode) {
      case 'vi':
        return '$count thiết bị';
      case 'ja':
        return '$count 台';
      case 'ko':
        return '$count개 기기';
      case 'zh':
        return '$count 个设备';
      default:
        return count == 1 ? '1 device' : '$count devices';
    }
  }

  String get hiGreeting => _t('hiGreeting');
  String get welcomeBack => _t('welcomeBack');
  String get myRooms => _t('myRooms');
  String get addNew => _t('addNew');
  String get frequentlyUsed => _t('frequentlyUsed');
  String get seeAll => _t('seeAll');

  String get bedRoom => _t('bedRoom');
  String get livingRoom => _t('livingRoom');
  String get studyRoom => _t('studyRoom');
  String get guestRoom => _t('guestRoom');

  String get fiveRooms => _t('fiveRooms');
  String get twoRooms => _t('twoRooms');
  String get oneRoom => _t('oneRoom');

  String get airCondition => _t('airCondition');
  String get ceilingFan => _t('ceilingFan');
  String get connected => _t('connected');
  String get disconnected => _t('disconnected');
  String get on => _t('on');
  String get off => _t('off');

  String get languageSettingsTitle => _t('languageSettingsTitle');
  String get choosePreferredLanguage => _t('choosePreferredLanguage');
  String get save => _t('save');
  String get languageSavedSuccessfully => _t('languageSavedSuccessfully');

  String get addNewRoom => _t('addNewRoom');
  String get enterRoomName => _t('enterRoomName');
  String get cancel => _t('cancel');
  String get add => _t('add');
  String get viewDevices => _t('viewDevices');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (l) => l.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const Map<String, Map<String, String>> _localizedValues = {
  'en': {
    'hiGreeting': 'Hi, User!',
    'welcomeBack': 'Welcome back to your smart Home.',
    'myRooms': 'My rooms',
    'addNew': 'Add New',
    'frequentlyUsed': 'Frequently Used',
    'seeAll': 'See All',
    'bedRoom': 'Bed Room',
    'livingRoom': 'Living Room',
    'studyRoom': 'Study Room',
    'guestRoom': 'Guest Room',
    'fiveRooms': '5 devices',
    'twoRooms': '2 devices',
    'oneRoom': '1 device',
    'airCondition': 'Air Condition',
    'ceilingFan': 'Ceiling Fan',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'on': 'On',
    'off': 'Off',
    'languageSettingsTitle': 'Language Settings',
    'choosePreferredLanguage': 'Choose your preferred language',
    'save': 'Save',
    'languageSavedSuccessfully': 'Language saved successfully',
    'addNewRoom': 'Add New Room',
    'enterRoomName': 'Enter room name',
    'cancel': 'Cancel',
    'add': 'Add',
    'viewDevices': 'View devices',
    'No rooms yet': 'No rooms yet',
    'Default': 'Default',
    'Vietnamese': 'Vietnamese',
    'Japanese': 'Japanese',
    'Korean': 'Korean',
    'Chinese': 'Chinese',
    'SmartHome': 'SmartHome',
    'Home': 'Home',
    'Hi': 'Hi',
    'Devices': 'Devices',
    'Rooms': 'Rooms',
    'Stats': 'Stats',
    'Scheduler': 'Scheduler',
    'Alerts': 'Alerts',
    'Settings': 'Settings',
    'Username': 'Username',
    'Unable to load webcam stream': 'Unable to load webcam stream',
    'Sign In': 'Sign In',
    'Sign Up': 'Sign Up',
    'Signing in...': 'Signing in...',
    'Signing up...': 'Signing up...',
    'Please fill all fields': 'Please fill all fields',
    'Passwords do not match': 'Passwords do not match',
    'Sign up success': 'Sign up success',
    'Email': 'Email',
    'Password': 'Password',
    'Re Password': 'Re Password',
    'Forgot Password?': 'Forgot Password?',
    'Go to Home': 'Go to Home',
    'Or': 'Or',
    'Already have an account? ': 'Already have an account? ',
    'example@gmail.com': 'example@gmail.com',
    '********': '********',
    '******': '******',
    '*******': '*******',
    'Device Video': 'Device Video',
    'Master Bedroom Camera': 'Master Bedroom Camera',
    'Add New Camera': 'Add New Camera',
    'Camera Name': 'Camera Name',
    'Video URL': 'Video URL',
    'Cameras': 'Cameras',
    'Live Feeds': 'Live Feeds',
    'Fire Alerts': 'Fire Alerts',
    'Mark all read': 'Mark all read',
    'Fire in progress': 'Fire in progress',
    'All clear. No fire detected.': 'All clear. No fire detected.',
    'Unknown zone': 'Unknown zone',
    'Fire alert at': 'Fire alert at',
    'View now': 'View now',
    'Close': 'Close',
    'No fire events in this session.': 'No fire events in this session.',
    'Temperature': 'Temperature',
    'Smoke': 'Smoke',
    'Acknowledge': 'Acknowledge',
    'Normal': 'Normal',
    'Active': 'Active',
    'Acknowledged': 'Acknowledged',
    'Resolved': 'Resolved',
    'Add new device': 'Add new device',
    'Add device': 'Add device',
    'Add Device': 'Add Device',
    'Add New Device': 'Add New Device',
    'Add room': 'Add room',
    'Add new room': 'Add new room',
    'Room name': 'Room name',
    'Delete room': 'Delete room',
    'Delete device': 'Delete device',
    'Edit device': 'Edit device',
    'This will remove the room and its devices.':
        'This will remove the room and its devices.',
    'This will remove the device.': 'This will remove the device.',
    'Delete': 'Delete',
    'More': 'More',
    'Device type': 'Device type',
    'Device name': 'Device name',
    'Enter device name': 'Enter device name',
    'Location': 'Location',
    'Home Location': 'Home Location',
    'Devices in this room': 'Devices in this room',
    'Select a room to control devices': 'Select a room to control devices',
    'Legend': 'Legend',
    'Use mouse wheel to zoom': 'Use mouse wheel to zoom',
    'On': 'On',
    'Off': 'Off',
    'Change Password': 'Change Password',
    'Old Password': 'Old Password',
    'New Password': 'New Password',
    'Confirm Password': 'Confirm Password',
    'Confirm New Password': 'Confirm New Password',
    'Current Password': 'Current Password',
    'Update Password': 'Update Password',
    'Profile Edit': 'Profile Edit',
    'Name': 'Name',
    'Address': 'Address',
    'Home Name': 'Home Name',
    'Save': 'Save',
    'abc': 'abc',
    'Linh': 'Linh',
    'Linh@gmail.com': 'Linh@gmail.com',
    'ngoi nha hanh puc': 'ngoi nha hanh puc',
    'Device Scheduler': 'Device Scheduler',
    'Start': 'Start',
    'End': 'End',
    'Action': 'Action',
    'Time': 'Time',
    'Edit': 'Edit',
    'Schedule': 'Schedule',
    'Schedule for': 'Schedule for',
    'updated!': 'updated!',
    'No scheduled actions found. Add a new one!':
        'No scheduled actions found. Add a new one!',
    'Add New Schedule (Not Implemented)': 'Add New Schedule (Not Implemented)',
    'Days of Week (Not editable yet)': 'Days of Week (Not editable yet)',
    'Mon': 'Mon',
    'Tue': 'Tue',
    'Wed': 'Wed',
    'Thu': 'Thu',
    'Fri': 'Fri',
    'Sat': 'Sat',
    'Sun': 'Sun',
    'Everyday': 'Everyday',
    'Turn On': 'Turn On',
    'Turn Off': 'Turn Off',
    'Account Settings': 'Account Settings',
    'Notification Settings': 'Notification Settings',
    'Appearance': 'Appearance',
    'Theme': 'Theme',
    'System Default': 'System Default',
    'Font Size': 'Font Size',
    'Medium': 'Medium',
    'About': 'About',
    'App Version': 'App Version',
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    'Email Preferences': 'Email Preferences',
    'Push Notifications': 'Push Notifications',
    'Sound Alerts': 'Sound Alerts',
    'Notification Center': 'Notification Center',
    'Control how and when you receive alerts.':
        'Control how and when you receive alerts.',
    'System': 'System',
    'Security': 'Security',
    'Energy': 'Energy',
    'Enable Notifications': 'Enable Notifications',
    'Turn on/off all notifications': 'Turn on/off all notifications',
    'Device Alerts': 'Device Alerts',
    'Device status & errors': 'Device status & errors',
    'Security Alerts': 'Security Alerts',
    'Intrusion & safety alerts': 'Intrusion & safety alerts',
    'Energy Usage Alerts': 'Energy Usage Alerts',
    'High power consumption warnings': 'High power consumption warnings',
    'Delivery Methods': 'Delivery Methods',
    'Receive alerts on device': 'Receive alerts on device',
    'Email Notifications': 'Email Notifications',
    'Receive alerts via email': 'Receive alerts via email',
    'Do Not Disturb': 'Do Not Disturb',
    'Mute notifications temporarily': 'Mute notifications temporarily',
    'Security Options': 'Security Options',
    'Two-Factor Authentication': 'Two-Factor Authentication',
    'Add extra security to your account': 'Add extra security to your account',
    'Biometric Login': 'Biometric Login',
    'Use fingerprint or face ID': 'Use fingerprint or face ID',
    'Login Activity': 'Login Activity',
    'Active now': 'Active now',
    '2 hours ago': '2 hours ago',
    'Yesterday': 'Yesterday',
    'Danger Zone': 'Danger Zone',
    'Log out from all devices': 'Log out from all devices',
    'This will log you out of all active sessions.':
        'This will log you out of all active sessions.',
    'Logout All Devices': 'Logout All Devices',
    'Chrome · Windows': 'Chrome · Windows',
    'Hanoi, Vietnam': 'Hanoi, Vietnam',
    'Ho Chi Minh City': 'Ho Chi Minh City',
    'Da Nang': 'Da Nang',
    'Application information': 'Application information',
    'Change your personal information': 'Change your personal information',
    'Edit Profile': 'Edit Profile',
    'Notifications': 'Notifications',
    'Language': 'Language',
    'Manage notification preferences': 'Manage notification preferences',
    'Password & authentication': 'Password & authentication',
    'Select application language': 'Select application language',
    'About Application': 'About Application',
    'Smart Home Manager': 'Smart Home Manager',
    'Version 1.0.0': 'Version 1.0.0',
    'Platform': 'Platform',
    'Desktop / Web': 'Desktop / Web',
    'Build': 'Build',
    '2025.02': '2025.02',
    'Developer': 'Developer',
    'HC Team': 'HC Team',
    'Legal & Support': 'Legal & Support',
    'Open Source Licenses': 'Open Source Licenses',
    'Contact Support': 'Contact Support',
    'Energy Statistics': 'Energy Statistics',
    'Energy Usage (kWh)': 'Energy Usage (kWh)',
    'Total Energy Consumption': 'Total Energy Consumption',
    'Highest consumer': 'Highest consumer',
    'Consumption by Device': 'Consumption by Device',
    'Consumption by Type': 'Consumption by Type',
    'Consumption Overview': 'Consumption Overview',
    'Day': 'Day',
    'Week': 'Week',
    'Month': 'Month',
    'Master Bedroom': 'Master Bedroom',
    'Smart Light': 'Smart Light',
    'Living Room TV': 'Living Room TV',
    'Living Room': 'Living Room',
    'Kitchen': 'Kitchen',
    'Bedroom': 'Bedroom',
    'Office': 'Office',
    'Kitchen Fridge': 'Kitchen Fridge',
    'Bedroom AC': 'Bedroom AC',
    'Laptop Charger': 'Laptop Charger',
    'Living Room Lamp': 'Living Room Lamp',
    'Air Conditioner': 'Air Conditioner',
    'Washing Machine': 'Washing Machine',
    'TV': 'TV',
    'Lamp': 'Lamp',
    'Speaker': 'Speaker',
    'Oven': 'Oven',
    'Light': 'Light',
    'Night Lamp': 'Night Lamp',
    'PC': 'PC',
    'Desk Lamp': 'Desk Lamp',
    'Air Condition': 'Air Condition',
    'Lamp Light': 'Lamp Light',
    'Ceiling Fan': 'Ceiling Fan',
    'Kitchen Light': 'Kitchen Light',
    'Coffee Machine': 'Coffee Machine',
  },
  'vi': {
    'hiGreeting': 'Xin chào!',
    'welcomeBack': 'Chào mừng bạn quay lại nhà thông minh.',
    'myRooms': 'Phòng của tôi',
    'addNew': 'Thêm mới',
    'frequentlyUsed': 'Dùng thường xuyên',
    'seeAll': 'Xem tất cả',
    'bedRoom': 'Phòng ngủ',
    'livingRoom': 'Phòng khách',
    'studyRoom': 'Phòng làm việc',
    'guestRoom': 'Phòng khách',
    'fiveRooms': '5 thiết bị',
    'twoRooms': '2 thiết bị',
    'oneRoom': '1 thiết bị',
    'airCondition': 'Điều hòa',
    'ceilingFan': 'Quạt trần',
    'connected': 'Đã kết nối',
    'disconnected': 'Mất kết nối',
    'on': 'Bật',
    'off': 'Tắt',
    'languageSettingsTitle': 'Cài đặt ngôn ngữ',
    'choosePreferredLanguage': 'Chọn ngôn ngữ bạn muốn',
    'save': 'Lưu',
    'languageSavedSuccessfully': 'Đã lưu ngôn ngữ',
    'addNewRoom': 'Thêm phòng mới',
    'enterRoomName': 'Nhập tên phòng',
    'cancel': 'Hủy',
    'add': 'Thêm',
    'viewDevices': 'Xem thiết bị',
    'No rooms yet': 'Chua co phong',
    'Default': 'Mặc định',
    'Vietnamese': 'Tiếng Việt',
    'Japanese': 'Tiếng Nhật',
    'Korean': 'Tiếng Hàn',
    'Chinese': 'Tiếng Trung',
    'SmartHome': 'SmartHome',
    'Home': 'Trang chủ',
    'Hi': 'Chào',
    'Devices': 'Thiết bị',
    'Rooms': 'Phòng',
    'Stats': 'Thống kê',
    'Scheduler': 'Lịch',
    'Alerts': 'Cảnh báo',
    'Settings': 'Cài đặt',
    'Username': 'Tên người dùng',
    'Unable to load webcam stream': 'Không tải được luồng webcam',
    'Sign In': 'Đăng nhập',
    'Sign Up': 'Đăng ký',
    'Signing in...': 'Đang đăng nhập...',
    'Signing up...': 'Đang đăng ký...',
    'Please fill all fields': 'Vui lòng nhập đầy đủ thông tin',
    'Passwords do not match': 'Mật khẩu không khớp',
    'Sign up success': 'Đăng ký thành công',
    'Email': 'Email',
    'Password': 'Mật khẩu',
    'Re Password': 'Nhập lại mật khẩu',
    'Forgot Password?': 'Quên mật khẩu?',
    'Go to Home': 'Về trang chủ',
    'Or': 'Hoặc',
    'Already have an account? ': 'Đã có tài khoản? ',
    'example@gmail.com': 'example@gmail.com',
    '********': '********',
    '******': '******',
    '*******': '*******',
    'Device Video': 'Video thiết bị',
    'Master Bedroom Camera': 'Camera phòng ngủ chính',
    'Add New Camera': 'Thêm camera mới',
    'Camera Name': 'Tên camera',
    'Video URL': 'URL video',
    'Cameras': 'Camera',
    'Live Feeds': 'Luồng trực tiếp',
    'Fire Alerts': 'Cảnh báo cháy',
    'Mark all read': 'Đánh dấu đã đọc',
    'Fire in progress': 'Đang có cháy',
    'All clear. No fire detected.': 'An toàn, không có cháy.',
    'Unknown zone': 'Khu vực không xác định',
    'Fire alert at': 'Cảnh báo cháy tại',
    'View now': 'Xem ngay',
    'Close': 'Đóng',
    'No fire events in this session.': 'Không có sự kiện cháy trong phiên này.',
    'Temperature': 'Nhiệt độ',
    'Smoke': 'Khói',
    'Acknowledge': 'Xác nhận',
    'Normal': 'Bình thường',
    'Active': 'Đang hoạt động',
    'Acknowledged': 'Đã xác nhận',
    'Resolved': 'Đã xử lý',
    'Add new device': 'Thêm thiết bị mới',
    'Add device': 'Thêm thiết bị',
    'Add Device': 'Thêm thiết bị',
    'Add New Device': 'Thêm thiết bị mới',
    'Add room': 'Them phong',
    'Add new room': 'Them phong moi',
    'Room name': 'Ten phong',
    'Delete room': 'Xoa phong',
    'Delete device': 'Xoa thiet bi',
    'Edit device': 'Sua thiet bi',
    'This will remove the room and its devices.':
        'Thao tac nay se xoa phong va thiet bi.',
    'This will remove the device.': 'Thao tac nay se xoa thiet bi.',
    'Delete': 'Xoa',
    'More': 'Them',
    'Device type': 'Loai thiet bi',
    'Device name': 'Tên thiết bị',
    'Enter device name': 'Nhập tên thiết bị',
    'Location': 'Vị trí',
    'Home Location': 'Vị trí nhà',
    'Devices in this room': 'Thiết bị trong phòng',
    'Select a room to control devices': 'Chọn phòng để điều khiển thiết bị',
    'Legend': 'Chú giải',
    'Use mouse wheel to zoom': 'Dùng con lăn chuột để phóng to',
    'On': 'Bật',
    'Off': 'Tắt',
    'Change Password': 'Đổi mật khẩu',
    'Old Password': 'Mật khẩu cũ',
    'New Password': 'Mật khẩu mới',
    'Confirm Password': 'Xác nhận mật khẩu',
    'Confirm New Password': 'Xác nhận mật khẩu mới',
    'Current Password': 'Mật khẩu hiện tại',
    'Update Password': 'Cập nhật mật khẩu',
    'Profile Edit': 'Chỉnh sửa hồ sơ',
    'Name': 'Tên',
    'Address': 'Địa chỉ',
    'Home Name': 'Tên nhà',
    'Save': 'Lưu',
    'abc': 'abc',
    'Linh': 'Linh',
    'Linh@gmail.com': 'Linh@gmail.com',
    'ngoi nha hanh puc': 'ngoi nha hanh puc',
    'Device Scheduler': 'Lịch thiết bị',
    'Start': 'Bắt đầu',
    'End': 'Kết thúc',
    'Action': 'Hành động',
    'Time': 'Thời gian',
    'Edit': 'Chỉnh sửa',
    'Schedule': 'Lịch',
    'Schedule for': 'Lịch cho',
    'updated!': 'đã cập nhật!',
    'No scheduled actions found. Add a new one!':
        'Không có lịch nào. Hãy thêm mới!',
    'Add New Schedule (Not Implemented)': 'Thêm lịch mới (chưa hỗ trợ)',
    'Days of Week (Not editable yet)': 'Các ngày trong tuần (chưa chỉnh sửa)',
    'Mon': 'T2',
    'Tue': 'T3',
    'Wed': 'T4',
    'Thu': 'T5',
    'Fri': 'T6',
    'Sat': 'T7',
    'Sun': 'CN',
    'Everyday': 'Mỗi ngày',
    'Turn On': 'Bật',
    'Turn Off': 'Tắt',
    'Account Settings': 'Cài đặt tài khoản',
    'Notification Settings': 'Cài đặt thông báo',
    'Appearance': 'Giao diện',
    'Theme': 'Chủ đề',
    'System Default': 'Mặc định hệ thống',
    'Font Size': 'Cỡ chữ',
    'Medium': 'Trung bình',
    'About': 'Giới thiệu',
    'App Version': 'Phiên bản ứng dụng',
    'Privacy Policy': 'Chính sách bảo mật',
    'Terms of Service': 'Điều khoản dịch vụ',
    'Email Preferences': 'Tùy chọn email',
    'Push Notifications': 'Thông báo đẩy',
    'Sound Alerts': 'Âm thanh cảnh báo',
    'Notification Center': 'Trung tâm thông báo',
    'Control how and when you receive alerts.':
        'Kiểm soát cách và thời điểm nhận cảnh báo.',
    'System': 'Hệ thống',
    'Security': 'Bảo mật',
    'Energy': 'Năng lượng',
    'Enable Notifications': 'Bật thông báo',
    'Turn on/off all notifications': 'Bật/tắt tất cả thông báo',
    'Device Alerts': 'Cảnh báo thiết bị',
    'Device status & errors': 'Trạng thái & lỗi thiết bị',
    'Security Alerts': 'Cảnh báo bảo mật',
    'Intrusion & safety alerts': 'Cảnh báo xâm nhập & an toàn',
    'Energy Usage Alerts': 'Cảnh báo sử dụng năng lượng',
    'High power consumption warnings': 'Cảnh báo tiêu thụ điện cao',
    'Delivery Methods': 'Phương thức nhận',
    'Receive alerts on device': 'Nhận cảnh báo trên thiết bị',
    'Email Notifications': 'Thông báo qua email',
    'Receive alerts via email': 'Nhận cảnh báo qua email',
    'Do Not Disturb': 'Không làm phiền',
    'Mute notifications temporarily': 'Tạm tắt thông báo',
    'Security Options': 'Tùy chọn bảo mật',
    'Two-Factor Authentication': 'Xác thực hai yếu tố',
    'Add extra security to your account': 'Tăng cường bảo mật cho tài khoản',
    'Biometric Login': 'Đăng nhập sinh trắc',
    'Use fingerprint or face ID': 'Dùng vân tay hoặc Face ID',
    'Login Activity': 'Hoạt động đăng nhập',
    'Active now': 'Đang hoạt động',
    '2 hours ago': '2 giờ trước',
    'Yesterday': 'Hôm qua',
    'Danger Zone': 'Vùng nguy hiểm',
    'Log out from all devices': 'Đăng xuất khỏi mọi thiết bị',
    'This will log you out of all active sessions.':
        'Thao tác này sẽ đăng xuất mọi phiên đang hoạt động.',
    'Logout All Devices': 'Đăng xuất tất cả thiết bị',
    'Chrome · Windows': 'Chrome · Windows',
    'Hanoi, Vietnam': 'Hà Nội, Việt Nam',
    'Ho Chi Minh City': 'TP. Hồ Chí Minh',
    'Da Nang': 'Đà Nẵng',
    'Application information': 'Thông tin ứng dụng',
    'Change your personal information': 'Thay đổi thông tin cá nhân',
    'Edit Profile': 'Chỉnh sửa hồ sơ',
    'Notifications': 'Thông báo',
    'Language': 'Ngôn ngữ',
    'Manage notification preferences': 'Quản lý tùy chọn thông báo',
    'Password & authentication': 'Mật khẩu & xác thực',
    'Select application language': 'Chọn ngôn ngữ ứng dụng',
    'About Application': 'Về ứng dụng',
    'Smart Home Manager': 'Smart Home Manager',
    'Version 1.0.0': 'Phiên bản 1.0.0',
    'Platform': 'Nền tảng',
    'Desktop / Web': 'Desktop / Web',
    'Build': 'Bản dựng',
    '2025.02': '2025.02',
    'Developer': 'Nhà phát triển',
    'HC Team': 'Nhóm HC',
    'Legal & Support': 'Pháp lý & Hỗ trợ',
    'Open Source Licenses': 'Giấy phép mã nguồn mở',
    'Contact Support': 'Liên hệ hỗ trợ',
    'Energy Statistics': 'Thống kê năng lượng',
    'Energy Usage (kWh)': 'Mức tiêu thụ (kWh)',
    'Total Energy Consumption': 'Tổng tiêu thụ năng lượng',
    'Highest consumer': 'Tiêu thụ cao nhất',
    'Consumption by Device': 'Tiêu thụ theo thiết bị',
    'Consumption by Type': 'Tiêu thụ theo loại',
    'Consumption Overview': 'Tổng quan tiêu thụ',
    'Day': 'Ngày',
    'Week': 'Tuần',
    'Month': 'Tháng',
    'Master Bedroom': 'Phòng ngủ chính',
    'Smart Light': 'Đèn thông minh',
    'Living Room TV': 'TV phòng khách',
    'Living Room': 'Phòng khách',
    'Kitchen': 'Bếp',
    'Bedroom': 'Phòng ngủ',
    'Office': 'Văn phòng',
    'Kitchen Fridge': 'Tủ lạnh bếp',
    'Bedroom AC': 'Điều hòa phòng ngủ',
    'Laptop Charger': 'Sạc laptop',
    'Living Room Lamp': 'Đèn phòng khách',
    'Air Conditioner': 'Điều hòa',
    'Washing Machine': 'Máy giặt',
    'TV': 'TV',
    'Lamp': 'Đèn',
    'Speaker': 'Loa',
    'Oven': 'Lò nướng',
    'Light': 'Đèn',
    'Night Lamp': 'Đèn ngủ',
    'PC': 'PC',
    'Desk Lamp': 'Đèn bàn',
    'Air Condition': 'Điều hòa',
    'Lamp Light': 'Đèn ngủ',
    'Ceiling Fan': 'Quạt trần',
    'Kitchen Light': 'Đèn bếp',
    'Coffee Machine': 'Máy pha cà phê',
    'Connected': 'Đã kết nối',
    'Disconnected': 'Mất kết nối',
  },
  'ja': {
    'hiGreeting': 'こんにちは！',
    'welcomeBack': 'スマートホームへようこそ。',
    'myRooms': '部屋',
    'addNew': '追加',
    'frequentlyUsed': 'よく使う',
    'seeAll': 'すべて表示',
    'bedRoom': '寝室',
    'livingRoom': 'リビング',
    'studyRoom': '書斎',
    'guestRoom': 'ゲストルーム',
    'fiveRooms': '5 台',
    'twoRooms': '2 台',
    'oneRoom': '1 台',
    'airCondition': 'エアコン',
    'ceilingFan': 'シーリングファン',
    'connected': '接続済み',
    'disconnected': '未接続',
    'on': 'オン',
    'off': 'オフ',
    'languageSettingsTitle': '言語設定',
    'choosePreferredLanguage': '使用する言語を選択してください',
    'save': '保存',
    'languageSavedSuccessfully': '言語を保存しました',
    'addNewRoom': '新しい部屋を追加',
    'enterRoomName': '部屋名を入力',
    'cancel': 'キャンセル',
    'add': '追加',
    'viewDevices': 'デバイスを見る',
  },
  'ko': {
    'hiGreeting': '안녕하세요!',
    'welcomeBack': '스마트홈에 다시 오신 것을 환영합니다.',
    'myRooms': '내 방',
    'addNew': '추가',
    'frequentlyUsed': '자주 사용하는',
    'seeAll': '전체 보기',
    'bedRoom': '침실',
    'livingRoom': '거실',
    'studyRoom': '서재',
    'guestRoom': '게스트룸',
    'fiveRooms': '5개 기기',
    'twoRooms': '2개 기기',
    'oneRoom': '1개 기기',
    'airCondition': '에어컨',
    'ceilingFan': '실링 팬',
    'connected': '연결됨',
    'disconnected': '연결 끊김',
    'on': '켜짐',
    'off': '꺼짐',
    'languageSettingsTitle': '언어 설정',
    'choosePreferredLanguage': '사용할 언어를 선택하세요',
    'save': '저장',
    'languageSavedSuccessfully': '언어가 저장되었습니다',
    'addNewRoom': '새 방 추가',
    'enterRoomName': '방 이름 입력',
    'cancel': '취소',
    'add': '추가',
    'viewDevices': '기기 보기',
  },
  'zh': {
    'hiGreeting': '你好！',
    'welcomeBack': '欢迎回到你的智能家居。',
    'myRooms': '我的房间',
    'addNew': '新增',
    'frequentlyUsed': '常用设备',
    'seeAll': '查看全部',
    'bedRoom': '卧室',
    'livingRoom': '客厅',
    'studyRoom': '书房',
    'guestRoom': '客房',
    'fiveRooms': '5 个设备',
    'twoRooms': '2 个设备',
    'oneRoom': '1 个设备',
    'airCondition': '空调',
    'ceilingFan': '吊扇',
    'connected': '已连接',
    'disconnected': '未连接',
    'on': '开',
    'off': '关',
    'languageSettingsTitle': '语言设置',
    'choosePreferredLanguage': '选择你偏好的语言',
    'save': '保存',
    'languageSavedSuccessfully': '语言已保存',
    'addNewRoom': '添加新房间',
    'enterRoomName': '输入房间名称',
    'cancel': '取消',
    'add': '添加',
    'viewDevices': '查看设备',
  },
};
